### ISSUE TITLE
可以的、大神！你成功引起了我们的关注，哈哈

### ISSUE THREAD

**Issue by a526107856** [qzcool/Tianyancha#36]
要不要来天眼查工作呀-_-!

**Comment by a526107856** [comment]
可以不用selenium抓取吗？

**Comment by qzcool** [comment]
@a526107856 我知道肯定会有这么一天，谢谢邀请哈！具体岗位可以发我邮箱qiao.zhang.qz@outlook.com我看眼。用Selenium是因为我个人比较熟练，如果用Scrapy应该也是可以的，但只用Requests应该不行。

**Comment by a526107856** [comment]
目前我们主要在拉钩平台上发布招聘、你可以先看下哈。另外，大家都是做技术的、我是天眼查的爬虫之一、咱们可以客气点。
欢迎加我微信a526107856，有啥问题可以问我，你看下有兴趣的话，我帮你内推，希望有机会成为同事哈




------------------ 原始邮件 ------------------
发件人: "Qiao Zhang"<notifications@github.com>; 
发送时间: 2019年5月24日(星期五) 凌晨4:17
收件人: "qzcool/Tianyancha"<Tianyancha@noreply.github.com>; 
抄送: "王鹏权"<526107856@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [qzcool/Tianyancha] 可以的、大神！你成功引起了我们的关注，哈哈 (#36)




@a526107856 我知道肯定会有这么一天，谢谢邀请哈！具体岗位可以发我邮箱qiao.zhang.qz@outlook.com我看眼。用Selenium是因为我个人比较熟练，如果用Scrapy应该也是可以的，但只用Requests应该不行。

**Comment by qzcool** [comment]
优秀，好的，以后多交流。
